spring:
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        from: ${MAIL_FROM_ADDRESS}
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls.enable: ${MAIL_SMTP_STARTTLS}
          starttls.required: ${MAIL_SMTP_STARTTLS}